name: Build containera

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install qemu-user-static
          sudo apt install binfmt-support
      - name: Login gchr.io
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ROOTFS_PATH: ${{ secrets.ROOTFS_PATH }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u kolserdav --password-stdin
      - name: Build
        run: |
          sh -c "./src/scripts/build.sh"
          